#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MobileApp_Assignment.Resource", IsApplication=true)]

namespace MobileApp_Assignment
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int weight_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BakingHP = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Brownie = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Cupcake1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int TempBg = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Weightbg = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060012
			public const int btnConvertTemp = 2131099666;
			
			// aapt resource value: 0x7f060001
			public const int btnConvertTemperature = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int btnConvertWeight = 2131099650;
			
			// aapt resource value: 0x7f060013
			public const int btnHome = 2131099667;
			
			// aapt resource value: 0x7f060003
			public const int btnRecipes = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int imgRecipe = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int lblHome = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int lblIngredients = 2131099654;
			
			// aapt resource value: 0x7f06000b
			public const int lblRecipeDescription = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int lblRecipeTitle = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int lblSteps = 2131099655;
			
			// aapt resource value: 0x7f06000c
			public const int lblTempConversion = 2131099660;
			
			// aapt resource value: 0x7f060005
			public const int lblTitle = 2131099653;
			
			// aapt resource value: 0x7f060014
			public const int lblWeightConversion = 2131099668;
			
			// aapt resource value: 0x7f060018
			public const int linearLayout2 = 2131099672;
			
			// aapt resource value: 0x7f060008
			public const int lvRecipes = 2131099656;
			
			// aapt resource value: 0x7f06000e
			public const int radioGroupTemps = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int rbtnCel = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int rbtnFah = 2131099664;
			
			// aapt resource value: 0x7f060004
			public const int scrollView1 = 2131099652;
			
			// aapt resource value: 0x7f060016
			public const int spinner = 2131099670;
			
			// aapt resource value: 0x7f060011
			public const int txtConvertedTemp = 2131099665;
			
			// aapt resource value: 0x7f060017
			public const int txtConvertedWeight = 2131099671;
			
			// aapt resource value: 0x7f06000d
			public const int txtTemp = 2131099661;
			
			// aapt resource value: 0x7f060015
			public const int txtWeight = 2131099669;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int RecipeDlgFrg = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int RecipeLV = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int RecipeRow = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TempConversion = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int WeightConversion = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int home = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int temp = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int weight = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int weight_promt = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
